{
  "hash": "06964954b8d16068376e1b9546b22a1b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Teste _t_\"\nauthor:\n  - name: Paulo Barros\n    orcid: 0000-0001-9839-0796\n    email: pbarrosbio@gmail.com\n    affiliations:\n      - name: PPZ - UESB - GACOM\neditor_options: \n  chunk_output_type: console\ncsl: abnt_ipea.csl\nbibliography: ref.bib\n---\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistering fonts with R\n```\n\n\n:::\n:::\n\n\n<br>\n\n:::{.columns}\n:::{.column  width=\"30%\"}\n![William Sealy Gosset](https://www.madrimasd.org/blogs/matematicas/files/2019/04/1024px-William_Sealy_Gosset.jpg){width=\"200\" fig-align=\"left\"}\n:::\n:::{.column  width=\"70%\"}\nO Teste $\\large t$ de Student foi proposto por William Sealy Gosset. O nome \n_Student_ se deve ao fato de Gosset ser funcionário da cervejaria Guinness e\nutilizava o pseudônimo de Student em suas publicações. O teste $t$ utiliza a\n*distribuição $t$*, que pode ser imaginada com uma versão da distribuição\nnormal para pequenas amostras. Gosset precisava desta alternativa para comparar\nexperimentos na cervejaria, muitos com amostras pequenas. Gosset não tinha\nnenhuma intenção em causar impacto na estatística, seu teste buscava resolver\numa questão prática e aplicada dentro da sua área de atuação. Seu teste entretanto\né de enorme importância até hoje e destaca o quanto a significância de domínio\n(biológica, ecológica, econômica...) deve sempre preceder a significância\nestatística [@hector2021new].\n:::\n:::\n\n### Qual Teste $t$?\n\nExistem dois tipos de teste. \n\n  * Para duas amostras independentes;\n  \n  * Para duas amostras pareadas.\n  \nNo primeiro caso, nosso objetivo é comparar duas amostras obtidas de maneira\nindependente. Por exemplo: massa foliar de plantas submetidas a dois tipos\nde tratamento, peso de camundongos alimentados com dietas com dois teores de \nproteína, etc.\n\nNo caso de amostras paredas, não temos independência pois desejamos medir o\nefeito sob um mesmo grupo de indivíduos/amostas. Por exemplo: comprimento do\npelo de um grupo de Chinchilas antes e depois de submetidos a uma dieta, riqueza\nde espécies em uma área antes e depois de um episódio de queimada, etc.\n\nEm cada caso, os testes necessitam obedecer a premissas que veremos mais em\ndetalhes a seguir.\n\nOutro aspecto importante diz respeito a como formulamos a Hipótese Nula ($H_0$)\ne em consequência a Hipótese Alternativa ($H_a$). Cada gráfico mostra uma curva\nde distribuição $t$, e as áreas azuis $(\\alpha)$ representam as *regiões críticas*\nonde rejeitamos a hipótese nula ($H_0$). Vamos ver cada um:\n\n*** \n\n:::{.columns}\n:::{.column  width=\"35%\"}\n![](images/ttest1.png){width=\"350\"}\n:::\n:::{.column  width=\"65%\"}\n\n* A área azul está à esquerda da curva.\n\n* Esse teste é usado quando queremos saber **se a média é menor** que um valor específico.\n\n::: {.content-hidden when-format=\"pdf\"}\n| **$\\large H_0$**  | **$\\large H_a$**              |\n|--------------------|--------------------|\n| $\\mu_1 \\geq \\mu_2$ | $\\mu_1 < \\mu_2$    |\n\n: Cauda a esquerda {.striped .hover .tbl-forty}\n:::\n\n\\begin{tabular}{>{\\centering\\arraybackslash}m{3cm} >{\\centering\\arraybackslash}m{3cm}}\n\\toprule\n$H_0$ & $H_a$ \\\\\n\\midrule\n$\\mu_1 \\geq \\mu_2$ & $\\mu_1 < \\mu_2$ \\\\\n\\bottomrule\n\\end{tabular}\n\nRejeitamos $H_0$ se o valor de $t$ calculado cair na cauda esquerda da curva \n(menor que $t_0$).\n:::\n:::\n\n***\n\n:::{.columns}\n:::{.column  width=\"35%\"}\n![](images/ttest2.png){width=\"350\"}\n:::\n:::{.column  width=\"65%\"}\n\n* A área azul está à direita da curva.\n\n* Esse teste é usado quando queremos saber **se a média é maior** que um valor específico.\n\n::: {.content-hidden when-format=\"pdf\"}\n| **$\\large H_0$**  | **$\\large H_a$**              |\n|--------------------|--------------------|\n| $\\mu_1 \\leq \\mu_2$ | $\\mu_1 \\gt \\mu_2$    |\n\n: Cauda a direita {.striped .hover .tbl-forty}\n:::\n\n\\begin{tabular}{>{\\centering\\arraybackslash}m{3cm} >{\\centering\\arraybackslash}m{3cm}}\n\\toprule\n$H_0$ & $H_a$ \\\\\n\\midrule\n$\\mu_1 \\leq \\mu_2$ & $\\mu_1 > \\mu_2$ \\\\\n\\bottomrule\n\\end{tabular}\n\nRejeitamos $H_0$ se o valor de $t$ calculado cair na cauda direita da curva \n(maior que $t_0$).\n:::\n:::\n\n***\n\n:::{.columns}\n:::{.column  width=\"35%\"}\n![Adaptado de @larson2023estatistica](images/ttest3.png){width=\"350\"}\n:::\n:::{.column  width=\"65%\"}\n\n* Agora há duas regiões críticas, uma em cada cauda (esquerda e direita).\n\n * Esse teste é usado quando queremos saber **se a média é diferente**, seja para\n mais ou para menos.\n\n::: {.content-hidden when-format=\"pdf\"}\n| **$\\large H_0$**  | **$\\large H_a$**              |\n|--------------------|--------------------|\n| $\\mu_1 = \\mu_2$ | $\\mu_1 \\neq \\mu_2$    |\n\n: Bilateral {.striped .hover .tbl-forty}\n::: \n\n\n\n\\begin{tabular}{>{\\centering\\arraybackslash}m{3cm} >{\\centering\\arraybackslash}m{3cm}}\n\\toprule\n$H_0$ & $H_a$ \\\\\n\\midrule\n$\\mu_1 = \\mu_2$ & $\\mu_1 \\neq \\mu_2$ \\\\\n\\bottomrule\n\\end{tabular}\n\nRejeitamos $H_0$ se o valor de $t$ for muito pequeno ou muito grande\n(cair em qualquer uma das duas caudas).\n\nO valor de $\\alpha$ (nível de significância) é dividido ao meio: metade em cada cauda.\n:::\n:::\n\n::: {.callout-note}\n## Importante\n  \n  Para as próximas etapas nesta sessão utilizaremos dados do pacote `ecodados`,\n  vocês podem fazer a instalação rodando `devtools::install_github(\"paternogbc/ecodados\")`.\n  Este pacote é parte do excelente livro\n  [Análises Ecológicas no R de @da2022analises](https://analises-ecologicas.com/){target=\"_blank\"} e\n  é simplesmente um dos melhores livros dedicados a ciência de dados para Ecologia,\n  disponível gratuitamente na internet. Obrigado aos autores mais uma vez! \n  \n:::\n\n### Teste $t$ independente\n\nUm teste t baseado em duas amostras é usado para testar a diferença entre duas \nmédias populacionais $\\mu_1$ e $\\mu_2$ quando $\\sigma_1$ e $\\sigma_2$ são desconhecidos,\ne portanto usamos os desvios amostrais.\n\n\n$$t = \\frac{\\bar{x_1}-\\bar{x_2}}{s}\\sqrt{\\frac{n_1\\times n_2}{n_1 + n_2}}$$\n\nPremissas do Teste $t$:\n\n1. As amostras devem ser independentes\n2. As unidades amostrais são selecionadas aleatoriamente\n3. Distribuição normal (gaussiana) dos resíduos\n4. Homogeneidade da variância\n\n\n### Pacotes Necessários\n\n`car`, `ecodados`, `tidyverse`\n\n\n#### Exemplo 1\n\nUsaremos os dados de comprimento rostro-cloacal (CRC) de machos de anfíbios da\nespécie _Physalaemus nattereri_ (Anura:Leptodactylidae) amostrados em diferentes\nestações do ano.\n\n**Pergunta:** Existe diferença na média co CRC em _P. nattereri_ entre as estações?\n\n**Hipótese Nula:** As médias de CRC são iguais.\n\n**Hipótese Alternativa:** As médias de CRC são diferentes entre as estações.\n\nAntes de realizarmos o teste $t$, precisamos nos certificar de que nossos dados\natendem as premissas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse, quietly = TRUE)\n\ncrc_phy_nat <- ecodados::teste_t_var_igual\n\nglimpse(crc_phy_nat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 51\nColumns: 2\n$ CRC     <dbl> 3.82, 3.57, 3.67, 3.72, 3.75, 3.83, 3.85, 3.87, 3.93, 4.01, 4.…\n$ Estacao <chr> \"Chuvosa\", \"Chuvosa\", \"Chuvosa\", \"Chuvosa\", \"Chuvosa\", \"Chuvos…\n```\n\n\n:::\n:::\n\n\n[**QQ plot (Quantile-Quantile plot)** é um gráfico que compara os quantis dos seus dados com os quantis de uma distribuição teórica (geralmente normal) para verificar se os dados seguem essa distribuição.]{.aside}\n\nPara avaliar a normalidade dos resíduos podemos fazer visualmente através de um\n**QQ-Plot**.\n\nVamos falar em Regressão Linear em uma sessão futura, por enquanto saiba que estaremos\nutilizando um modelo super simples de $CRC \\sim Estação$ (CRC _em função das_ Estações)\ne capturando os resíduos deste modelo para testar sua normalidade. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod <- lm(CRC ~ Estacao, data = crc_phy_nat)\n\ncar::qqPlot(mod)\n```\n\n::: {.cell-output-display}\n![](07_t_test_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22 26\n```\n\n\n:::\n:::\n\n\nOs pontos se aproximam bastante da reta, o que nos sugere que nossos resíduos\n**são normalmente distribuídos**.\n\nPodemos ainda utilizar o teste de Shapiro-Wilk e avaliar a normalidade e a\nheterocedasticidade (homogeneidade) da variância.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(residuals(mod))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(mod)\nW = 0.98307, p-value = 0.6746\n```\n\n\n:::\n:::\n\n\nTestando a variância com o teste de Levene\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::leveneTest(mod)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in leveneTest.default(y = y, group = group, ...): group coerced to\nfactor.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  1  1.1677 0.2852\n      49               \n```\n\n\n:::\n:::\n\n\nA Hipótese nula de ambos os testes é a de que os resíduos apresentam distribuição\nnormal (Shapiro-Wilk) ou a variância é homogênea (Levene). Portanto na hora de\ninterpretar os p-valores:\n\n* $\\large p<0.05$: Rejeitamos $H_0$, resíduos não seguem normalidade/homogeneidade\nde variância.\n\n* $\\large p>0.05$: Deixamos de rejeitar $H_0$, resíduos são normais e variância é\nhomogênea.\n\nUma vez satisfeitas as premissas, podemos prosseguir e realizar o teste $t$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nteste_T <- t.test(CRC ~ Estacao, data = crc_phy_nat, var.equal = TRUE)\n\nteste_T\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  CRC by Estacao\nt = 4.1524, df = 49, p-value = 0.000131\nalternative hypothesis: true difference in means between group Chuvosa and group Seca is not equal to 0\n95 percent confidence interval:\n 0.2242132 0.6447619\nsample estimates:\nmean in group Chuvosa    mean in group Seca \n             3.695357              3.260870 \n```\n\n\n:::\n:::\n\n\nObserve o argumento `var.equal=TRUE`, isso informa a função que nossa variância\né homogênea. Isto é importante, pois em caso de variâncias não homogêneas há uma\nalteração no estimador utilizado para calcular a estatística $t$.\n\nAo apresentar os seu resultados inclua:\n\ni. A estatística $t$: $t = 4.1524$\n\nii. O p-valor: $p-value = 0.000131$\n\niii. Graus de Liberdade: $df = 49$\n\niv. Diferenca entre as médias: $0.434$\n\nUsando a função `tidy` do pacote `broom` você pode montar uma tabela mais amigável\ncom todos esses dados além de outros interessantes como intervalo de confiança.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gt)\n\n\noptions(scipen = 0)\nlabels <- c(\"Diferença Entre as Médias\",\"Media_1\",\"Media_2\",\"Estatística t\",\"p-valor\",\"Gl\",\"IC Inf\",\"IC Sup\")\n\nbroom::tidy(teste_T) |>\n  select(estimate:conf.high) |>\n  rename_all(~labels) |>\n  pivot_longer(everything(),values_to = \"Valor\",names_to = \"Desc\") |>\n  gt() |>\n  fmt_number(\n    columns = Valor,\n    decimals = 2,\n    rows = Desc != \"p-valor\" & Desc != \"Gl\"\n  ) %>%\n  fmt_number(\n    columns = Valor,\n    decimals = 0,\n    rows = Desc == \"Gl\"\n  ) %>%\n  cols_label(\n    Desc = \"Descrição\",\n    Valor = \"Valor\"\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"dxikxuxudh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dxikxuxudh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dxikxuxudh thead, #dxikxuxudh tbody, #dxikxuxudh tfoot, #dxikxuxudh tr, #dxikxuxudh td, #dxikxuxudh th {\n  border-style: none;\n}\n\n#dxikxuxudh p {\n  margin: 0;\n  padding: 0;\n}\n\n#dxikxuxudh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dxikxuxudh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dxikxuxudh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dxikxuxudh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dxikxuxudh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dxikxuxudh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dxikxuxudh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dxikxuxudh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dxikxuxudh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dxikxuxudh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dxikxuxudh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dxikxuxudh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dxikxuxudh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dxikxuxudh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dxikxuxudh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dxikxuxudh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dxikxuxudh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dxikxuxudh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dxikxuxudh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dxikxuxudh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dxikxuxudh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dxikxuxudh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dxikxuxudh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dxikxuxudh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dxikxuxudh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dxikxuxudh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dxikxuxudh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dxikxuxudh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dxikxuxudh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dxikxuxudh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dxikxuxudh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dxikxuxudh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dxikxuxudh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dxikxuxudh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dxikxuxudh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dxikxuxudh .gt_left {\n  text-align: left;\n}\n\n#dxikxuxudh .gt_center {\n  text-align: center;\n}\n\n#dxikxuxudh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dxikxuxudh .gt_font_normal {\n  font-weight: normal;\n}\n\n#dxikxuxudh .gt_font_bold {\n  font-weight: bold;\n}\n\n#dxikxuxudh .gt_font_italic {\n  font-style: italic;\n}\n\n#dxikxuxudh .gt_super {\n  font-size: 65%;\n}\n\n#dxikxuxudh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dxikxuxudh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dxikxuxudh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dxikxuxudh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dxikxuxudh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dxikxuxudh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dxikxuxudh .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#dxikxuxudh .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#dxikxuxudh div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Desc\">Descrição</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Valor\">Valor</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Desc\" class=\"gt_row gt_left\">Diferença Entre as Médias</td>\n<td headers=\"Valor\" class=\"gt_row gt_right\">0.43</td></tr>\n    <tr><td headers=\"Desc\" class=\"gt_row gt_left\">Media_1</td>\n<td headers=\"Valor\" class=\"gt_row gt_right\">3.70</td></tr>\n    <tr><td headers=\"Desc\" class=\"gt_row gt_left\">Media_2</td>\n<td headers=\"Valor\" class=\"gt_row gt_right\">3.26</td></tr>\n    <tr><td headers=\"Desc\" class=\"gt_row gt_left\">Estatística t</td>\n<td headers=\"Valor\" class=\"gt_row gt_right\">4.15</td></tr>\n    <tr><td headers=\"Desc\" class=\"gt_row gt_left\">p-valor</td>\n<td headers=\"Valor\" class=\"gt_row gt_right\">0.0001310152</td></tr>\n    <tr><td headers=\"Desc\" class=\"gt_row gt_left\">Gl</td>\n<td headers=\"Valor\" class=\"gt_row gt_right\">49</td></tr>\n    <tr><td headers=\"Desc\" class=\"gt_row gt_left\">IC Inf</td>\n<td headers=\"Valor\" class=\"gt_row gt_right\">0.22</td></tr>\n    <tr><td headers=\"Desc\" class=\"gt_row gt_left\">IC Sup</td>\n<td headers=\"Valor\" class=\"gt_row gt_right\">0.64</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nOutra opção é apresentar um gráfico de BoxPlot com as médias para cada estação e\nas observações.\n\n::: {.content-visible when-format=\"html\"}\n\n::: {.cell .fig-cap-location-margin}\n\n```{.r .cell-code}\nextrafont::loadfonts(quiet = TRUE)\n\nggplot(data = crc_phy_nat, aes(x = Estacao, y = CRC, color = Estacao)) + \n    labs(x = \"Estações\", \n         y = expression(paste(\"CRC (mm) - \", italic(\"P. nattereri\")))) +\n    geom_boxplot(fill = c(\"#606c38\", \"#dda15e\"), color = \"black\", \n                 outlier.shape = NA) +\n    geom_jitter(shape = 21, position = position_jitter(0.1), \n                cex = 3, alpha = 0.7, stroke = .8,\n                fill = \"grey60\") +\n    scale_color_manual(values = c(\"black\", \"black\")) +\n    annotate(\"text\",\n             label =\"t = 4.1524\",\n             size = 4,\n             x = \"Seca\",\n             y = 4.6,\n             hjust = 0,\n             family = \"Ubuntu\") +\n    annotate(\"text\",\n               label =\"DF = 49\",\n               size = 4,\n               x = \"Seca\",\n               y = 4.5,\n               hjust = 0,\n               family = \"Ubuntu\") +\n    annotate(\"text\",\n               label =\"Estimate: 0.434\",\n               size = 4,\n               x = \"Seca\",\n               y = 4.4,\n               hjust = 0,\n               family = \"Ubuntu\") +\n    annotate(\"text\",\n               label =\"p-value = 0.000131\",\n               size = 4,\n               x = \"Seca\",\n               y = 4.3,\n               hjust = 0,\n               family = \"Ubuntu\") +\n    theme_classic(base_size = 14,\n                  base_family = \"Ubuntu\") +\n    theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![Código adaptado de @da2022analises](07_t_test_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nextrafont::loadfonts(quiet = TRUE)\nggplot(data = crc_phy_nat, aes(x = Estacao, y = CRC, color = Estacao)) + \n    labs(x = \"Estações\", \n         y = expression(paste(\"CRC (mm) - \", italic(\"P. nattereri\")))) +\n    geom_boxplot(fill = c(\"#606c38\", \"#dda15e\"), color = \"black\", \n                 outlier.shape = NA) +\n    geom_jitter(shape = 21, position = position_jitter(0.1), \n                cex = 3, alpha = 0.7, stroke = .8,\n                fill = \"grey60\") +\n    scale_color_manual(values = c(\"black\", \"black\")) +\n    annotate(\"text\",\n             label =\"t = 4.1524\",\n             size = 4,\n             x = \"Seca\",\n             y = 4.6,\n             hjust = 0) +\n    annotate(\"text\",\n               label =\"DF = 49\",\n               size = 4,\n               x = \"Seca\",\n               y = 4.5,\n               hjust = 0) +\n    annotate(\"text\",\n               label =\"Estimate: 0.434\",\n               size = 4,\n               x = \"Seca\",\n               y = 4.4,\n               hjust = 0) +\n    annotate(\"text\",\n               label =\"p-value = 0.000131\",\n               size = 4,\n               x = \"Seca\",\n               y = 4.3,\n               hjust = 0) +\n    theme_classic(base_size = 14) +\n    theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](07_t_test_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n:::\n\n### Teste $t$ pareado\n\n\n\n\n\n",
    "supporting": [
      "07_t_test_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}