{
  "hash": "422c82c68d1333a58889194800221d86",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Estatística no R\"\ntitle-slide-attributes:\n    data-background-image: ../images/LogoTidy.png\n    data-background-size: 300px\n    data-background-position: 80% 50%\nsubtitle: \"Ciência de Dados amigável com **_tidyverse_**\"\nauthor: \n  - name: PAULO BARROS\n    affiliation: \"PhD candidate Animal Sciences at PPZ-UESB\" \nformat: \n  revealjs:\n    output-file: intro-tidy-revealjs.html\n    theme: [default, pb_reveal.scss]\n    logo: images/pb_logo.png\n    highlight-style: zenburn\n    slide-number: true\nbibliography: ref.bib\ncsl: abnt_ipea.csl\nexecute: \n  echo: true\n  include: true\neditor_options: \n  chunk_output_type: console\n---\n\n::: {.cell}\n\n:::\n\n\n\n\n## Hi there! {{< fa hand-peace  >}}\n\n::: {.v-center-container}\n\n:::{.columns}\n:::{.column  width=\"40%\"}\n![](images/ArtePBCartoon.png){width=\"700px\"}\n:::\n:::{.column  .smallbf  width=\"60%\"}\n### Paulo Barros\n\n<br>\n\n{{< fa  graduation-cap >}} **2024 - PhD Zootecnia (Melhoramento Genético Animal) (PPZ-UESB)**\n\n{{< fa  graduation-cap >}} 2024 - MSc Genética, Biodiversidade e Conservação (PPGGBC-UESB)\n\n{{< fa  graduation-cap >}} 2020 - Biologia com Ênfase em Genética (UESB)\n\n<br>\n\n***\n:::{.center-col}\n:::{.columns } \n:::{.column  width=\"25%\"}\n{{< fa crow size=3x >}}\n\nConsultoria Ambiental\n:::\n:::{.column  width=\"25%\"}\n{{< fa laptop-code size=3x >}}\n\nConsultoria Estatística\n:::\n:::{.column  width=\"25%\"}\n{{< fa person-chalkboard size=3x >}}\n\nCursos e Mentorias\n:::\n:::{.column  width=\"25%\"}\n{{< fa box size=3x >}}\n\nDesenvolvimento de Pacotes\n:::\n:::\n:::\n\n:::\n:::\n:::\n\n\n## O que aprender pra aprender R...\n\n::: {.v-center-container}\n:::{.columns}\n:::{.column  width=\"50%\"}\n::: {.fragment}\n\n### O jeito difícil...\n\n![](https://cdn.myportfolio.com/45214904-6a61-4e23-98d6-b140f8654a40/2231d847-adce-477c-bdcc-b05be343eb15_rw_1920.jpg?h=675b39d4a0768d3a05e8f3d90b65b85f){width=\"100%\"}\n:::\n:::\n:::{.column  width=\"\"}\n::: {.fragment}\n\n### O jeito fácil...\n\n![](images/mist.png){width=\"100%\"}\n:::\n:::\n:::\n:::\n\n::: aside\nImagem por [Allison Horst.](https://allisonhorst.com/everything-else){target=\"_blank\"}\n:::\n\n\n## Encontre sua motivação individual\n\n\n![](https://cdn.myportfolio.com/45214904-6a61-4e23-98d6-b140f8654a40/d65eb83f-66e4-4760-8c1f-29d336d1d6df.png?h=9b917065e8502455cd1c4791492b2199){width=\"100%\"}\n\n\n::: aside\nImagem por [Allison Horst.](https://allisonhorst.com/everything-else){target=\"_blank\"}\n:::\n\n## Vantagens em aprender R\n\n:::{.v-center-container}\n\n:::{.columns}\n:::{.column  width=\"\" .incremental}\n\n* Independência pra rodar suas análises\n\n* Um maior entendimento da sua própria pesquisa\n\n* Oportunidades de carreira\n\n* **Reproducibilidade:** caminha pra se tornar _industry standard_ \n:::\n\n:::{.column  width=\"\"}\n\n:::{.fragment}\n![](images/scott.jpg){width=\"400\" fig-align=\"center\"}\n\n**e principalmente...**\n\nVocê não ter que sair correndo atrás de alguém faltando 15 dias pra sua\nqualificação/defesa querendo aprender R pra rodar tuas análises e estatística\npra interpretar teus dados.\n:::\n\n:::\n:::\n  \n:::\n\n\n\n\n\n# Download & Instalação {background-color=\"#2b2d41ff\" background-image=\"images/install.png\" background-size=\"400px\"background-position=\"80% 50%\"}\n\n\n## Instalando R e R Studio\n\n::: {.v-center-container}\n\n:::{.columns}\n:::{.column  width=\"40%\"}\n{{< fa brands r-project size=2x >}}\n\n[The Comprehensive R Archive Network - CRAN](https://cran.r-project.org/){target=\"_blank\"}\n\n+ **R-4.5.0** \n  + (2025-04-11, How About a Twenty-Six) \n\n:::\n:::{.column  width=\"10%\"}\n:::\n:::{.column  width=\"40%\"}\n![](https://posit.co/wp-content/themes/Posit/assets/images/posit-logo-2024.svg){width=\"300px\"}\n\n[RStudio IDE](https://posit.co/downloads/){target=\"_blank\"}\n\n+ Version 2025.05.0 Build 496\n\n:::\n:::\n:::\n\n\n# R Studio {background-color=\"#2b2d41ff\" background-image=\"https://forum.posit.co/uploads/default/original/3X/c/f/cfd969809f9ee8c5ad30a776ce43728c64cca03d.png\" background-size=\"300px\" background-position=\"60% 50%\"}\n\nAmbiente de Desenvolvimento <br>\npara linguagem R\n\n\n## O básico do R\n\n\n:::{.columns}\n:::{.column  width=\"45%\"}\n**Matemática Básica**\n\n::: {.cell}\n\n```{.r .cell-code}\n1 / 200 * 30\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.15\n```\n\n\n:::\n\n```{.r .cell-code}\n(59 + 73 + 2) / 3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 44.66667\n```\n\n\n:::\n:::\n\n\n**Comentários**\n\nQualquer texto precedido de # não é lido como código.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Comentários são úteis\n# pra documentar o código\n\n1:5 # cria uma sequência de 1 a 5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1 2 3 4 5\n```\n\n\n:::\n:::\n\n\n\n:::\n:::{.column  width=\"5%\"}\n:::\n:::{.column  width=\"45%\"}\n**Objetos**\n\n`object_name <- value`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimes <- c(2, 3, 5, 7, 11, 13)\n\nprimes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  2  3  5  7 11 13\n```\n\n\n:::\n:::\n\n\n`c()` é a função de **c**ombinar elementos. \n\n**Nomes de Objetos**\n\nTodo objeto no R deve ter o nome iniciado por letra, e só podem conter `_` ou `.`\n\n```\ni_use_snake_case\notherPeopleUseCamelCase\nsome.people.use.periods\nAnd_aFew.People_RENOUNCEconvention\n```\n:::\n:::\n\n## Pacotes\n\nPacotes são conjuntos de funções combinadas que extendem a capacidade da linguagem R.\n\nAtualmente são mais de **22 mil pacotes** no [CRAN](https://cran.r-project.org/web/packages/index.html){target=\"_blank\"}\n\n:::{.columns}\n:::{.column  width=\"40%\"}\n**Instalação**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"tidyverse\")\n```\n:::\n\n\n**Carregamento**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n<br>\n\n::: {.callout-note}\n## Atenção\n\nInstalamos uma única vez (Por versão do R). Carregamos os pacotes todas as vezes\nque precisamos utilizar em nossos scripts.  \n:::\n\n:::\n:::{.column  width=\"2%\"}\n:::\n:::{.column  width=\"55%\"}\n**Datasets**\n\nA maioria dos pacotes vem com _datasets_ de exemplos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(package=\"nome_do_pacote\")\n```\n:::\n\n\nPara listar todos os datasets\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(package = .packages(all.available = TRUE))\n```\n:::\n\n\n\n:::\n:::\n\n\n# _tidyverse_ {background-color=\"#FFFFFF\" background-image=\"images/tidyverse.png\" background-size=\"700px\"background-position=\"65% 50%\"}\n\nPorque estatística e programação<br>\njá são difíceis pra cacete...\n\n\n## Uma maneira elegante e intuitiva de trabalhar com dados...\n\nVamos dar uma olhada no dataset `iris` que já vem com o R.\n\nO comando `str()` nos diz a **estrutura** dos dados.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t150 obs. of  5 variables:\n $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...\n $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...\n $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...\n $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...\n $ Species     : Factor w/ 3 levels \"setosa\",\"versicolor\",..: 1 1 1 1 1 1 1 1 1 1 ...\n```\n\n\n:::\n:::\n\n\nO comando `head()` exibe as primeiras observações de um objeto.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(iris, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Sepal.Length Sepal.Width Petal.Length Petal.Width Species\n1           5.1         3.5          1.4         0.2  setosa\n2           4.9         3.0          1.4         0.2  setosa\n3           4.7         3.2          1.3         0.2  setosa\n4           4.6         3.1          1.5         0.2  setosa\n5           5.0         3.6          1.4         0.2  setosa\n6           5.4         3.9          1.7         0.4  setosa\n7           4.6         3.4          1.4         0.3  setosa\n8           5.0         3.4          1.5         0.2  setosa\n9           4.4         2.9          1.4         0.2  setosa\n10          4.9         3.1          1.5         0.1  setosa\n```\n\n\n:::\n:::\n\n\n\n\n\n## Uma maneira elegante e intuitiva de trabalhar com dados...\n\n:::{.fragment}\n**Base R**\n\n::: {.cell}\n\n```{.r .cell-code}\nsetosa_data <- iris[iris$Species == \"setosa\", ]\n\nsepal_data <- setosa_data[, grepl(\"^Sepal\",names(setosa_data))]\n\nsepal_means <- colMeans(sepal_data)\n\nas.data.frame(t(sepal_means))\n```\n:::\n\n:::\n\n:::{.fragment}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length Sepal.Width\n1        5.006       3.428\n```\n\n\n:::\n:::\n\n:::\n\n:::{.columns}\n:::{.column  width=\"48%\"}\n:::{.fragment}\n**Tidy Way**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse, quietly = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\niris |>\n  filter(Species == \"setosa\") |>\n  select(starts_with(\"Sepal\")) |>\n  summarize_all(list(mean = mean))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length_mean Sepal.Width_mean\n1             5.006            3.428\n```\n\n\n:::\n:::\n\n:::\n\n:::\n:::{.column  width=\"2%\"}\n:::\n:::{.column  width=\"50%\"}\n:::{.fragment}\n**Em português...**\n\nCom o _dataset_ `iris` |>\n\n**Filtre** pela `species` = `setosa` |>\n\n**Selecione** colunas que **começam com** `Sepal` |>\n\n**Calcule as médias**.\n:::\n\n:::\n:::\n\n# Visualização de Dados {background-color=\"#170b28ff\" background-image=\"images/dataviz.png\" background-size=\"400px\"background-position=\"65% 50%\"}\n\nA gramática dos gráficos com **_ggplot2_**\n\n## Grammar of graphics\n\n![](images/grammar_of_graphics.png){width=\"700\"}\n\n## Estrutura básica de um _ggplot_\n\n\n\n::: {.cell layout-align=\"center\" width='6' height='6'}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(iris) +\n  aes(x = Species, y = Sepal.Length) +\n  geom_boxplot(aes(fill = Species)) +\n  scale_fill_manual(values = c(\"#f7a072\",\"#0fa3b1\",\"#b5e2fa\"))+\n  labs(title=\"Distribuição de Comprimento de Sépala\",\n       x = \"Espécies\",\n       y = \"Comprimento Sépala\") +\n  theme_classic(base_size = 14, base_family = \"DejaVu Sans\")\n```\n\n::: {.cell-output-display}\n![](intro_tidy_slides_files/figure-revealjs/unnamed-chunk-15-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n## Visualizando distribuições\n\n:::{.columns}\n:::{.column  width=\"\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(iris, aes(x=Sepal.Width)) +\n  geom_histogram() +\n  theme_bw(base_size = 22)\n```\n\n::: {.cell-output-display}\n![](intro_tidy_slides_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n:::\n:::{.column  width=\"\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(iris, aes(x=Sepal.Width)) +\n  geom_histogram(color = \"#32746d\",\n                 fill=\"#cad2c5\",\n                 alpha = 0.6) +\n  theme_bw(base_size = 22,\n           base_family = \"Ubuntu\")\n```\n\n::: {.cell-output-display}\n![](intro_tidy_slides_files/figure-revealjs/unnamed-chunk-17-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n:::\n:::\n\n## Relacionamento entre variáveis\n\n:::{.columns}\n:::{.column  width=\"\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(iris, \n  aes(x = Sepal.Length,Petal.Length)) +\n  geom_point() +\n  theme_classic(base_size = 24,\n                base_family = \"Ubuntu\")\n```\n\n::: {.cell-output-display}\n![](intro_tidy_slides_files/figure-revealjs/unnamed-chunk-18-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n:::\n:::{.column  width=\"\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(iris,\n    aes(x = Sepal.Length,Petal.Length)) +\n  geom_point(aes(fill = Species),\n             size = 3,\n             shape = 21,\n             alpha = 0.75) +\n  geom_smooth(method = \"lm\",\n              linetype = 2,\n              linewidth = 0.5,\n              color = \"grey30\",\n              se = FALSE) +\n  theme_classic(base_size = 24,\n                base_family = \"Ubuntu\") +\n  theme(legend.position = \"top\",\n        legend.direction = \"horizontal\")\n```\n\n::: {.cell-output-display}\n![](intro_tidy_slides_files/figure-revealjs/unnamed-chunk-19-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n:::\n:::\n\n## Ciclo de uma Análise de Dados\n:::{.v-center-container}\n\n![](images/dc-cicle.png){width=\"800\"}\n  \n:::\n\n\n# Manipulação de<br>dados com **_dplyr_**{background-color=\"#FFFFFF\" background-image=\"images/dplyr_bg.png\" background-size=\"600px\"background-position=\"65% 50%\"}\n\n## Importando Dados\n\nOs tipos de arquivos mais comuns são as planilhas tipo excel (`.xls`, `.xlsx`) e\narquivos de texto delimitados (`.csv`,`.tsv`,`.txt`).\n\n#### Planilhas\n\nPacote `readxl` fornece uma maneira simples de importar arquivos tipo Excel.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- read_excel(\"data/dados_var.xlsx\")\n```\n:::\n\n\nPor padrão `read_excel()` sempre importa **a primeira folha de uma planilha**.\n\nPosso listar as folhas dentro de uma planilha com `excel_sheets()` ...\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexcel_sheets(\"data/dados_var.xlsx\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Média--Variância-DP-CV\" \"Temperatura\"           \n```\n\n\n:::\n:::\n\n\ne importar uma folha diferente pelo **nome** ou **ordem**  com o argumento `sheet`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_folha_2 <- read_excel(\"data/dados_var.xlsx\", sheet = 2)\n```\n:::\n\n\n## Importando Dados\n\n#### Planilhas\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  Tabela 2. Número de pacientes homens e mulheres e os motivos que…¹ ...2  ...3 \n  <chr>                                                              <chr> <chr>\n1 <NA>                                                               <NA>  <NA> \n2 Motivos                                                            Home… Mulh…\n3 Restauração                                                        20    35   \n4 Implante                                                           5     20   \n5 Limpeza                                                            15    30   \n6 Extração                                                           25    15   \n# ℹ abbreviated name:\n#   ¹​`Tabela 2. Número de pacientes homens e mulheres e os motivos que frequentam o consultório odontológico durante o período de um ano.`\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(dados_folha_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 13\n  Temperatura     Segunda Terça Quarta Quinta Sexta Sábado Domingo ...9  MÉDIA\n  <chr>             <dbl> <dbl>  <dbl>  <dbl> <dbl>  <dbl>   <dbl> <lgl> <lgl>\n1 Primeira semana      27    32     31     30    29     30      31 NA    NA   \n2 Segunda semana       25    30     32     27    29     28      32 NA    NA   \n# ℹ 3 more variables: VARIÂNCIA <lgl>, DP <lgl>, CV <lgl>\n```\n\n\n:::\n:::\n\n\n## Importando Dados\n\n#### Planilhas\n\nPodemos definir além da folha um **intervalo de células** na mesma notação do Excel.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- read_excel(\"data/dados_var.xlsx\", sheet = 1, range = \"A3:C9\")\n\ndados_folha_2 <- read_excel(\"data/dados_var.xlsx\", sheet = 2, range = \"A1:H3\")\n```\n:::\n\n\nAgora nossos dados foram importados corretamente {{< fa thumbs-up >}}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  Motivos     Homens Mulheres\n  <chr>        <dbl>    <dbl>\n1 Restauração     20       35\n2 Implante         5       20\n3 Limpeza         15       30\n4 Extração        25       15\n5 Prótese         15       14\n6 Clareamento      1        4\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(dados_folha_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 8\n  Temperatura     Segunda Terça Quarta Quinta Sexta Sábado Domingo\n  <chr>             <dbl> <dbl>  <dbl>  <dbl> <dbl>  <dbl>   <dbl>\n1 Primeira semana      27    32     31     30    29     30      31\n2 Segunda semana       25    30     32     27    29     28      32\n```\n\n\n:::\n:::\n\n\n## Importando Dados\n\n#### Arquivos `.csv`\n\nSão arquivos separados por vírgula. O pacote `readr` possui duas funções para\nleitura de arquivos `.csv`. \n\n:::{.columns}\n:::{.column  width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npatos <- read_csv(\"data/dadosPatos.csv\")\n\nhead(patos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  GG      PCC   CPT   APT   LPT   LCX   LSC\n  <chr> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n1 NM     1850  189.  51.4 110.   66.4 105. \n2 NM     1645  175.  57.8 109.   62.1 107. \n3 NM     1935  175.  42.4 123.   55.9 119. \n4 NM     2015  173.  55.0 121.   58.4 115. \n5 NF     1145  139.  48.6  92.5  46.1  85.6\n6 NF     1100  151.  45.8  97.6  66.3  75.8\n```\n\n\n:::\n:::\n\n:::\n:::{.column  width=\"5%\"}\n\n:::\n:::{.column  width=\"40%\"}\nEm alguns casos nosso arquivo pode não ter um cabeçalho com o nome\ndas variáveis.\n\nO argumento `header = FALSE` garante que a primeira linha não seja\nlida como cabeçalhos neste caso.\n\n:::\n:::\n\nA função `read_csv()` faz a leitura de um arquivo padrão **separado por vírgulas**,\nentretanto, alguns programas exportam `.csv` com ponto e vírgula como separador.\n\nPra isso temos a função `read_csv2()`. O processo de importação é idêntico.\n\n## Comandos úteis\n\n`str()` exibe a estrutura dos dados\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(patos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspc_tbl_ [16 × 7] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ GG : chr [1:16] \"NM\" \"NM\" \"NM\" \"NM\" ...\n $ PCC: num [1:16] 1850 1645 1935 2015 1145 ...\n $ CPT: num [1:16] 189 175 175 173 139 ...\n $ APT: num [1:16] 51.4 57.9 42.4 55 48.6 ...\n $ LPT: num [1:16] 110.3 108.6 123.4 121.2 92.5 ...\n $ LCX: num [1:16] 66.4 62.1 55.9 58.4 46.1 ...\n $ LSC: num [1:16] 105.4 106.9 118.9 114.6 85.6 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   GG = col_character(),\n  ..   PCC = col_double(),\n  ..   CPT = col_double(),\n  ..   APT = col_double(),\n  ..   LPT = col_double(),\n  ..   LCX = col_double(),\n  ..   LSC = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n\n\n:::\n:::\n\n\n## Comandos úteis\n\n`glimpse()` uma visão mais organizada da estrutura dos dados\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(patos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 16\nColumns: 7\n$ GG  <chr> \"NM\", \"NM\", \"NM\", \"NM\", \"NF\", \"NF\", \"NF\", \"NF\", \"CM\", \"CM\", \"CM\", …\n$ PCC <dbl> 1850, 1645, 1935, 2015, 1145, 1100, 1270, 1170, 3085, 3075, 3075, …\n$ CPT <dbl> 189.14, 174.84, 175.24, 173.25, 138.89, 150.94, 144.80, 155.00, 24…\n$ APT <dbl> 51.41, 57.85, 42.36, 55.05, 48.57, 45.81, 39.79, 44.81, 70.03, 62.…\n$ LPT <dbl> 110.30, 108.57, 123.44, 121.24, 92.46, 97.60, 108.17, 92.15, 144.6…\n$ LCX <dbl> 66.41, 62.09, 55.90, 58.41, 46.06, 66.32, 45.39, 57.04, 62.30, 58.…\n$ LSC <dbl> 105.36, 106.89, 118.92, 114.60, 85.57, 75.83, 99.73, 82.29, 129.23…\n```\n\n\n:::\n:::\n\n\n`names()` lista o nome das colunas ou de itens de um objeto\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(patos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"GG\"  \"PCC\" \"CPT\" \"APT\" \"LPT\" \"LCX\" \"LSC\"\n```\n\n\n:::\n:::\n\n\n## Seleção de Colunas\n\nA função `select()` do pacote `dplyr` nos permite selecionar colunas no dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(patos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"GG\"  \"PCC\" \"CPT\" \"APT\" \"LPT\" \"LCX\" \"LSC\"\n```\n\n\n:::\n:::\n\n\n:::{.columns}\n:::{.column  width=\"\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(patos, GG,PCC,APT)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 16 × 3\n   GG      PCC   APT\n   <chr> <dbl> <dbl>\n 1 NM     1850  51.4\n 2 NM     1645  57.8\n 3 NM     1935  42.4\n 4 NM     2015  55.0\n 5 NF     1145  48.6\n 6 NF     1100  45.8\n 7 NF     1270  39.8\n 8 NF     1170  44.8\n 9 CM     3085  70.0\n10 CM     3075  62.7\n11 CM     3075  56.0\n12 CM     2635  65.5\n13 CF     1710  61.4\n14 CF     1835  65.5\n15 CF     2035  56.4\n16 CF     1880  61.6\n```\n\n\n:::\n:::\n\nO primeiro argumento é o nome do dataset, seguido das colunas.\n:::\n:::{.column  width=\"\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(patos, GG,APT:LSC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 16 × 5\n   GG      APT   LPT   LCX   LSC\n   <chr> <dbl> <dbl> <dbl> <dbl>\n 1 NM     51.4 110.   66.4 105. \n 2 NM     57.8 109.   62.1 107. \n 3 NM     42.4 123.   55.9 119. \n 4 NM     55.0 121.   58.4 115. \n 5 NF     48.6  92.5  46.1  85.6\n 6 NF     45.8  97.6  66.3  75.8\n 7 NF     39.8 108.   45.4  99.7\n 8 NF     44.8  92.2  57.0  82.3\n 9 CM     70.0 145.   62.3 129. \n10 CM     62.7 139.   58.8 126. \n11 CM     56.0 147.   73.7 131. \n12 CM     65.5 126.   61.4 135. \n13 CF     61.4 109.   61.5 110. \n14 CF     65.5 106.   46.7  99.7\n15 CF     56.4 108.   57.5 107. \n16 CF     61.6 117.   59.1 106. \n```\n\n\n:::\n:::\n\nPodemos informar um intervalo de colunas com `inicio:fim`\n:::\n:::\n\n## Auxiliares de Seleção\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Sepal.Length\" \"Sepal.Width\"  \"Petal.Length\" \"Petal.Width\"  \"Species\"     \n```\n\n\n:::\n:::\n\n\n`starts_with()` Permite selecionar colunas que começam com um termo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(iris, starts_with(\"Petal\")) |> head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Petal.Length Petal.Width\n1          1.4         0.2\n2          1.4         0.2\n3          1.3         0.2\n```\n\n\n:::\n:::\n\n\n`ends_with()` Permite selecionar colunas que terminam com um termo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(iris, ends_with(\"Length\")) |> head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length Petal.Length\n1          5.1          1.4\n2          4.9          1.4\n3          4.7          1.3\n```\n\n\n:::\n:::\n\n\n`contains()` Permite selecionar colunas que contenham o termo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(iris, contains(\".\")) |> head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length Sepal.Width Petal.Length Petal.Width\n1          5.1         3.5          1.4         0.2\n2          4.9         3.0          1.4         0.2\n3          4.7         3.2          1.3         0.2\n```\n\n\n:::\n:::\n\n\n## Filtrando colunas\n\nA função `filter()` nos permite filtrar observações com base em condições.\n\nAs condições são avaliadas logicamente retornando em `TRUE` ou `FALSE`.\n\n:::{.columns}\n:::{.column  width=\"20%\"}\nOperadores:\n\nIgualdade:  `==`\n\nDiferença: `!=`\n\nComparação:\n<br>`>` `<` `>=` `<=` \n\nLógicos:\n  \n  * E (And) `&` \n  \n  * Ou (or) `|`\n\n:::\n:::{.column  width=\"80%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(iris,\n       Species == \"setosa\",\n       Petal.Length > 1.5) |>\n       head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length Sepal.Width Petal.Length Petal.Width Species\n1          5.4         3.9          1.7         0.4  setosa\n2          4.8         3.4          1.6         0.2  setosa\n3          5.7         3.8          1.7         0.3  setosa\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(iris, Species != \"versicolor\", \n    Sepal.Length >= 5 &  Sepal.Length < 5.3 ) |>\n    head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length Sepal.Width Petal.Length Petal.Width Species\n1          5.1         3.5          1.4         0.2  setosa\n2          5.0         3.6          1.4         0.2  setosa\n3          5.0         3.4          1.5         0.2  setosa\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n## Transformando e Criando variáveis\n\nO comando `mutate()` nos permite criar novas variáveis ou alterar as existentes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmutate(patos, PCC_KG = PCC/1000) |>\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  GG      PCC   CPT   APT   LPT   LCX   LSC PCC_KG\n  <chr> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>\n1 NM     1850  189.  51.4 110.   66.4 105.    1.85\n2 NM     1645  175.  57.8 109.   62.1 107.    1.64\n3 NM     1935  175.  42.4 123.   55.9 119.    1.94\n4 NM     2015  173.  55.0 121.   58.4 115.    2.02\n5 NF     1145  139.  48.6  92.5  46.1  85.6   1.14\n6 NF     1100  151.  45.8  97.6  66.3  75.8   1.1 \n```\n\n\n:::\n:::\n\n\nPor padrão a nova variável é adicionada ao final do dataset, mas esse comportamento\npode ser modificado usando os argumentos `.before` ou `.after` e explicitando \nantes ou depois de qual coluna desejamos nossa nova variável.\n\n## Operador **_pipe_**\n\nO operador `|>` (_pipe_) liga operações em um fluxo contínuo da **esquerda para a\ndireita**.\n\nO _pipe_ original `%>%` surgiu com o `tidyverse`, seu impacto foi tão grande na\nlinguagem que há alguns anos atrás os desenvolvedores do R incluíram um operador\nnativo na linguagem.\n\nUtilizando o _pipe_ podemos realizar uma sequência de inúmeras operações evitando\na criação de objetos intermediários para armazenar os resultados.\n\nNo fluxo o **objeto à esquerda** será o alvo da **operação da direita**.\n\nNum fluxo com o _pipe_ o operador sempre deve aparecer ao final da linha em caso\nde quebra:\n\n\n::: {.cell}\n\n```{.r .cell-code}\niris |>\n  head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length Sepal.Width Petal.Length Petal.Width Species\n1          5.1         3.5          1.4         0.2  setosa\n2          4.9         3.0          1.4         0.2  setosa\n3          4.7         3.2          1.3         0.2  setosa\n```\n\n\n:::\n:::\n\n\nIsto aqui causa um erro:\n\n\n::: {.cell}\n\n```{.r .cell-code}\niris\n|> head(3)\n```\n:::\n\n\n<br>\n\n```\nError: unexpected '|>' in \"|>\"\n``` \n\n# Análise<br>Exploratória de Dados {background-color=\"#170b28ff\" background-image=\"images/data-science.png\" background-size=\"400px\"background-position=\"65% 50%\"}\n\n## Medidas de Posição\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- read_excel(\"data/dados_var.xlsx\", sheet = 1, range = \"A3:C9\")\n```\n:::\n\n\nA função `summarise()` do pacote `dplyr` nos permite gerar estatísticas descritivas\n\n:::{.columns}\n:::{.column  width=\"\"}\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |>\n  summarise(Media_H = mean(Homens),\n            Media_M = mean(Mulheres),\n            Mediana_H = median(Homens),\n            Mediana_M = median(Mulheres))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  Media_H Media_M Mediana_H Mediana_M\n    <dbl>   <dbl>     <dbl>     <dbl>\n1    13.5    19.7        15      17.5\n```\n\n\n:::\n:::\n\n:::\n:::{.column  width=\"\"}\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |>\n  summarise(across(Homens:Mulheres,\n              list(media = mean,\n              mediana = median),\n              .names = \"{.col}_{.fn}\" ))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  Homens_media Homens_mediana Mulheres_media Mulheres_mediana\n         <dbl>          <dbl>          <dbl>            <dbl>\n1         13.5             15           19.7             17.5\n```\n\n\n:::\n:::\n\n:::\n:::\n\n## Medidas de Dispersão\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |>\n  summarise(across(Homens,\n              list(min = min,\n              max = max,\n              range = range,\n              dp = sd,\n              var = var),\n              .names = \"{.col}_{.fn}\" ))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  Homens_min Homens_max Homens_range Homens_dp Homens_var\n       <dbl>      <dbl>        <dbl>     <dbl>      <dbl>\n1          1         25            1      9.03       81.5\n2          1         25           25      9.03       81.5\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |>\n  summarise(across(Homens:Mulheres,\n              list(quartis = quantile),\n              .names = \"{.col}_{.fn}\" ))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  Homens_quartis Mulheres_quartis\n           <dbl>            <dbl>\n1            1                4  \n2            7.5             14.2\n3           15               17.5\n4           18.8             27.5\n5           25               35  \n```\n\n\n:::\n:::\n\n\n## `summary()`\n\nA função nativa `summary()` nos fornece um rol de estatísticas descritivas\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |>\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Motivos              Homens         Mulheres    \n Length:6           Min.   : 1.00   Min.   : 4.00  \n Class :character   1st Qu.: 7.50   1st Qu.:14.25  \n Mode  :character   Median :15.00   Median :17.50  \n                    Mean   :13.50   Mean   :19.67  \n                    3rd Qu.:18.75   3rd Qu.:27.50  \n                    Max.   :25.00   Max.   :35.00  \n```\n\n\n:::\n:::\n\n\nEsta função embora limitada no rol de estatísticas fornecidas, é muito útil para\num diagnóstico rápido dos dados. Ela nos permite avaliar o número de dados perdidos (`NA`) bem como valores fora do intervalo esperado, nossos _outliers_.\n\n\n## Descritivas segmentadas\n\nNa grande maioria das vezes precisamos calcular estatísticas descritivas agrupadas\npor níveis de variáveis categóricas. O pacote `rstatix` é muito eficiente nessa tarefa.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rstatix)\n\niris |>\n  group_by(Species) |>\n  get_summary_stats(everything(),\n                    type = \"mean_sd\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 5\n   Species    variable         n  mean    sd\n   <fct>      <fct>        <dbl> <dbl> <dbl>\n 1 setosa     Sepal.Length    50 5.01  0.352\n 2 setosa     Sepal.Width     50 3.43  0.379\n 3 setosa     Petal.Length    50 1.46  0.174\n 4 setosa     Petal.Width     50 0.246 0.105\n 5 versicolor Sepal.Length    50 5.94  0.516\n 6 versicolor Sepal.Width     50 2.77  0.314\n 7 versicolor Petal.Length    50 4.26  0.47 \n 8 versicolor Petal.Width     50 1.33  0.198\n 9 virginica  Sepal.Length    50 6.59  0.636\n10 virginica  Sepal.Width     50 2.97  0.322\n11 virginica  Petal.Length    50 5.55  0.552\n12 virginica  Petal.Width     50 2.03  0.275\n```\n\n\n:::\n:::\n\n\nA função `group_by()` do `dplyr` agrupa o nossos dados pelos níveis do fator `Species`,\npermitindo que as estatísticas sejam calculadas segmentadas e não como um todo para cada\nvariável.\n\nVariando o argumento `type` temos acesso a diversas estatísticas. Experimente utilizar\n`type = \"full\"`. \n\n\n# Inferência Estatística {background-color=\"#5181c1ff\" background-image=\"images/inference.png\" background-size=\"600px\"background-position=\"65% 50%\"}\n\n\n## Pacotes necessários\n\nNesta sessão utilizaremos alguns pacotes auxiliares, caso não tenham instalado ainda:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(`car`, `tidyverse`, `ggpubr`, `agricolae`, `devtools`))\n```\n:::\n\n\nUtilizaremos também dados do pacote `ecodados`, vocês podem fazer a instalação rodando `devtools::install_github(\"paternogbc/ecodados\")`. \n\nEste pacote é parte do excelente livro [Análises Ecológicas no R de @da2022analises](https://analises-ecologicas.com/){target=\"_blank\"} e é simplesmente\num dos melhores livros dedicados a ciência de dados para Ecologia, disponível\ngratuitamente na internet. Obrigado aos autores mais uma vez! \n\n\n\n## Teste $\\large t$ para duas amostras independentes\n\nUm teste t baseado em duas amostras é usado para testar a diferença entre duas \nmédias populacionais $\\mu_1$ e $\\mu_2$ quando $\\sigma_1$ e $\\sigma_2$ são desconhecidos,\ne portanto usamos os desvios amostrais.\n\n$$t = \\frac{\\bar{x_1}-\\bar{x_2}}{s}\\sqrt{\\frac{n_1\\times n_2}{n_1 + n_2}}$$\n\n**Premissas do Teste $t$:**\n\n1. As amostras devem ser independentes\n2. As unidades amostrais são selecionadas aleatoriamente\n3. Distribuição normal (gaussiana) dos resíduos\n4. Homogeneidade da variância\n\n\n## Teste $\\large t$ para duas amostras independentes\n\n#### Exemplo\n\nUsaremos os dados de comprimento rostro-cloacal (CRC) de machos de anfíbios da\nespécie _Physalaemus nattereri_ (Anura:Leptodactylidae) amostrados em diferentes\nestações do ano.\n\n**Pergunta:** Existe diferença na média co CRC em _P. nattereri_ entre as estações?\n\n**Hipótese Nula:** As médias de CRC são iguais.\n\n**Hipótese Alternativa:** As médias de CRC são diferentes entre as estações.\n\n\nAntes de realizarmos o teste $t$, precisamos nos certificar de que nossos dados\natendem as premissas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse, quietly = TRUE)\n\ncrc_phy_nat <- ecodados::teste_t_var_igual\n\nglimpse(crc_phy_nat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 51\nColumns: 2\n$ CRC     <dbl> 3.82, 3.57, 3.67, 3.72, 3.75, 3.83, 3.85, 3.87, 3.93, 4.01, 4.…\n$ Estacao <chr> \"Chuvosa\", \"Chuvosa\", \"Chuvosa\", \"Chuvosa\", \"Chuvosa\", \"Chuvos…\n```\n\n\n:::\n:::\n\n\n## Teste $\\large t$ para duas amostras independentes\n\n#### Checando premissas\n\n**QQ Plot**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod <- lm(CRC ~ Estacao, data = crc_phy_nat)\n\n(qq <- car::qqPlot(mod))\n```\n\n::: {.cell-output-display}\n![](intro_tidy_slides_files/figure-revealjs/unnamed-chunk-52-1.png){fig-align='center' width=960}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22 26\n```\n\n\n:::\n:::\n\n\n## Teste $\\large t$ para duas amostras independentes\n\n#### Checando premissas\n\nPodemos ainda utilizar o teste de Shapiro-Wilk e avaliar a normalidade \n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(residuals(mod))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(mod)\nW = 0.98307, p-value = 0.6746\n```\n\n\n:::\n:::\n\n\ne a heterocedasticidade (homogeneidade) da variância com o teste de Levene\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::leveneTest(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  1  1.1677 0.2852\n      49               \n```\n\n\n:::\n:::\n\n\n## Teste $\\large t$ para duas amostras independentes\n\nUma vez satisfeitas as premissas, podemos prosseguir e realizar o teste $t$:\n\n:::{.columns}\n:::{.column  width=\"45%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nteste_T <- t.test(CRC ~ Estacao,\n                  data = crc_phy_nat,\n                  var.equal = TRUE)\n\nteste_T\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  CRC by Estacao\nt = 4.1524, df = 49, p-value = 0.000131\nalternative hypothesis: true difference in means between group Chuvosa and group Seca is not equal to 0\n95 percent confidence interval:\n 0.2242132 0.6447619\nsample estimates:\nmean in group Chuvosa    mean in group Seca \n             3.695357              3.260870 \n```\n\n\n:::\n:::\n\n\n:::\n:::{.column  width=\"5%\"}\n:::\n:::{.column  width=\"45%\"}\nAo apresentar os seu resultados inclua:\n\ni. A estatística $t$: $t = 4.1524$\n\nii. O p-valor: $p-value = 0.000131$\n\niii. Graus de Liberdade: $df = 49$\n\niv. Diferenca entre as médias: $0.434$\n:::\n:::\n\n\n## Teste $\\large t$ para duas amostras independentes\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nextrafont::loadfonts(quiet = TRUE)\n\nggplot(data = crc_phy_nat, aes(x = Estacao, y = CRC, color = Estacao)) + \n    labs(x = \"Estações\", \n         y = expression(paste(\"CRC (mm) - \", italic(\"P. nattereri\")))) +\n    geom_boxplot(fill = c(\"#606c38\", \"#dda15e\"), color = \"black\", \n                 outlier.shape = NA, width = .3) +\n    geom_jitter(shape = 21, position = position_jitter(0.1), \n                cex = 3, alpha = 0.7, stroke = .8,\n                fill = \"grey60\") +\n    scale_color_manual(values = c(\"black\", \"black\")) +\n    annotate(\"text\",\n             label =\"t = 4.1524\",\n             size = 4,\n             x = \"Seca\",\n             y = 4.6,\n             hjust = 0,\n             family = \"Ubuntu\") +\n    annotate(\"text\",\n               label =\"DF = 49\",\n               size = 4,\n               x = \"Seca\",\n               y = 4.5,\n               hjust = 0,\n               family = \"Ubuntu\") +\n    annotate(\"text\",\n               label =\"Estimate: 0.434\",\n               size = 4,\n               x = \"Seca\",\n               y = 4.4,\n               hjust = 0,\n               family = \"Ubuntu\") +\n    annotate(\"text\",\n               label =\"p-value = 0.000131\",\n               size = 4,\n               x = \"Seca\",\n               y = 4.3,\n               hjust = 0,\n               family = \"Ubuntu\") +\n    theme_classic(base_size = 14,\n                  base_family = \"Ubuntu\") +\n    theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](intro_tidy_slides_files/figure-revealjs/unnamed-chunk-56-1.png){width=960}\n:::\n:::\n\n\n## Teste $t$ pareado\n\nNo teste $t$ pareado temos duas observações da mesma unidade amostral subetida\nao tratamento/efeito de interesse. O nosso objetivo é determinar se a diferença\nentre observações é zero.\n\n![Adaptado de @larson2023estatistica](images/samples.png){.lightbox width=\"400\"}\n\nPremissas:\n\n1. As unidades amostrais são selecionadas aleatoriamente\n2. As observações *não são independentes*\n3. Distribuição normal (gaussiana) dos valores da diferença para cada par\n\n\n## Teste $t$ pareado\n\n#### Exemplo\n\nNovamente vamos utilizar dados do pacote `ecodados` seguindo o exemplo disponível\nem @da2022analises. Vamos utilizar dados de riqueza de espécies de artrópodes em\numa área antes e depois de um processo de queimada.\n\n**Pergunta:** A riqueza de espécies de artrópodes é afetada pelas queimadas?\n\n**Hipótese Nula:** A riqueza de espécies é igual antes e depois.     \n\n\n::: {.cell}\n\n```{.r .cell-code}\nart_rich <- ecodados::teste_t_pareado\n\nart_rich |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 54\nColumns: 3\n$ Areas   <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…\n$ Riqueza <int> 92, 74, 96, 89, 76, 80, 62, 100, 50, 137, 54, 89, 116, 66, 79,…\n$ Estado  <chr> \"Pre-Queimada\", \"Pre-Queimada\", \"Pre-Queimada\", \"Pre-Queimada\"…\n```\n\n\n:::\n\n```{.r .cell-code}\nart_rich |>\n  count(Estado)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Estado  n\n1 Pos-Queimada 27\n2 Pre-Queimada 27\n```\n\n\n:::\n:::\n\n\n\n## Teste $t$ pareado\n\n#### Exemplo\n\nA função é a mesma `t.test()`, porém precisamos informar que agora estamos avaliando\ndados pareados, isso é feito pelo argumento `paired = TRUE`. Uma outra diferença\né que para o teste pareado, não podemos utilizar a notação de fórmula, precisamos\ndeclarar explicitamente nossos dois vetores de observações. O restante da análise\nsegue a anterior. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nrich_antes <- art_rich |>\n  filter(Estado == \"Pre-Queimada\") |>\n  pull(Riqueza)\n\nrich_depois <- art_rich |>\n  filter(Estado == \"Pos-Queimada\") |>\n  pull(Riqueza)\n\npar_T <- t.test(x = rich_antes, y = rich_depois, paired = TRUE)\n\npar_T\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  rich_antes and rich_depois\nt = 7.5788, df = 26, p-value = 4.803e-08\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 32.47117 56.63994\nsample estimates:\nmean difference \n       44.55556 \n```\n\n\n:::\n:::\n\n\n## Teste $t$ pareado\n\n#### Exemplo\n\nComo no exemplo anterior podemos apresentar nossos resultados de maneira gráfica.\nA função `ggpaired()` do pacote `ggpubr` nos fornece uma maneira bastante didática\nde apresentar nossos resultados.\n\n:::{.columns}\n:::{.column  width=\"\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nggpubr::ggpaired(art_rich, x = \"Estado\", y = \"Riqueza\",\ncolor = \"Estado\", line.color = \"gray\", line.size = 0.8,\npalette = c(\"#606c38\", \"#dda15e\"), width = 0.5,\npoint.size = 4, xlab = \"Estado das localidades\",\nylab = \"Riqueza de Espécies\") +\nexpand_limits(y = c(0, 150)) +\ntheme_classic(base_size = 14, base_family = \"Ubuntu\") +\n  theme(legend.direction = \"horizontal\",\n        legend.position = \"top\")\n```\n:::\n\n:::\n:::{.column  width=\"\"}\n\n::: {.cell .fig-cap-location-margin layout-align=\"center\" width='6' height='5' lightbox='{\"group\":\"r-graph\"}'}\n::: {.cell-output-display}\n![Código adaptado de @da2022analises](intro_tidy_slides_files/figure-revealjs/unnamed-chunk-60-1.png){fig-align='center' width=960}\n:::\n:::\n\n:::\n:::\n\n\n\n\n## Correlação\n\n> Uma **correlação** é uma relação entre duas variáveis. Os dados podem ser\nrepresentados por pares ordenados (x, y), sendo x a **variável independente**\n(ou explanatória) e y a **variável dependente** (ou resposta). [@larson2023estatistica]\n\n:::{.columns}\n:::{.column  width=\"\"}\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_pib_co2 <- tibble(\n  PIB = c(1.7, 1.2, 2.5, 2.8, 3.6, 2.2, 0.8, 1.5, 2.4, 5.9),\n  CO2 = c(552.6, 462.3, 475.4, 374.3, 748.5, 400.9, 253.0, 318.6, 496.8, 1180.6)\n)\n\ndados_pib_co2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 2\n     PIB   CO2\n   <dbl> <dbl>\n 1   1.7  553.\n 2   1.2  462.\n 3   2.5  475.\n 4   2.8  374.\n 5   3.6  748.\n 6   2.2  401.\n 7   0.8  253 \n 8   1.5  319.\n 9   2.4  497.\n10   5.9 1181.\n```\n\n\n:::\n:::\n\n\n:::\n:::{.column  width=\"\"}\n\n::: {.cell layout-align=\"center\" width='5' height='6' lightbox='{\"group\":\"r-graph\"}'}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(ggtext)\n\nggplot(dados_pib_co2,\n       aes(x = PIB, y = CO2)) +\n  geom_point(shape = 21, size =4, fill = \"grey70\", color = \"black\")+\n  theme_bw(base_size = 14, base_family = \"Ubuntu\") +\n  scale_x_continuous(breaks = 1:6) +\n  scale_y_continuous(breaks = seq(0,1200,by = 200))+\n  labs(title = \"Relação entre PIB e a quantidade de CO2 emitida,\n       para amostra com 10 países.\",\n       x = \"PIB <br> (em trilhões de dólares)\",\n       y = \"CO<sub>2</sub> <br> (em milhões de toneladas métricas)\") +\n  theme(axis.title = element_markdown())\n```\n\n::: {.cell-output-display}\n![](intro_tidy_slides_files/figure-revealjs/unnamed-chunk-62-1.png){fig-align='center' width=960}\n:::\n:::\n\n:::\n:::\n\n\n\n## Correlação de Pearson\n\nMais uma vez usaremos dados do `ecodados` de [@da2022analises]. Neste exemplo, \navaliaremos a correlação entre a altura do tronco e o tamanho da raiz medidos em 35\nindivíduos de uma espécie vegetal arbustiva.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\narbustos <- ecodados::correlacao\narbustos |> glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 35\nColumns: 2\n$ Tamanho_raiz   <dbl> 10.177049, 6.622634, 7.773629, 11.055257, 4.487274, 11.…\n$ Tamanho_tronco <dbl> 19.54383, 17.13558, 19.50681, 21.57085, 13.22763, 21.62…\n```\n\n\n:::\n:::\n\n\nUtilizaremos a função `cor.test()` explicitando que queremos o coeficiente de \nPearson no argumento `method=\"pearson\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(arbustos$Tamanho_raiz,\n         arbustos$Tamanho_tronco,\n         method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  arbustos$Tamanho_raiz and arbustos$Tamanho_tronco\nt = 11.49, df = 33, p-value = 4.474e-13\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.7995083 0.9457816\nsample estimates:\n      cor \n0.8944449 \n```\n\n\n:::\n:::\n\n\n## Correlação\n\n\n::: {.cell .fig-cap-location-margin}\n\n```{.r .cell-code  code-fold=\"true\"}\narbustos <- ecodados::correlacao\n\nggplot(data = arbustos, aes(x = Tamanho_raiz,\ny = Tamanho_tronco)) +\nlabs(x = \"Tamanho da raiz (m)\", y = \"Altura do tronco (m)\") +\n  geom_smooth(method = lm, se = FALSE, color = \"#3e5c76\",\nlinetype = \"solid\", linewidth=0.7) +\ngeom_point(size = 4, shape = 21, fill = \"#dc2f02\", alpha = 0.8) +\nannotate(\"text\",\n         x = 14, y = 14,\n         label = \"r = 0.89, P < 0.001\",\n         color = \"black\", size = 5,\n         family = \"Ubuntu\") +\n\ntheme_classic(base_size = 14, base_family = \"Ubuntu\") +\ntheme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![Adaptado de @da2022analises](intro_tidy_slides_files/figure-revealjs/fig-cor-1.png){#fig-cor width=960}\n:::\n:::\n\n\n## Regressão Linear Simples\n\nA regressão linear simples é usada para analisar a relação entre uma **variável preditora** (plotada no\neixo-X) e uma **variável resposta** (plotada no eixo-Y). As duas variáveis devem ser contínuas. Diferente\ndas correlações, a regressão assume uma relação de causa e efeito entre as variáveis. O valor da\nvariável preditora (X) causa, direta ou indiretamente, o valor da variável resposta (Y). Assim, Y é uma\nfunção linear de X [@da2022analises].\n\n$$\\Large y = \\beta_0+\\beta_1 X_i + \\varepsilon_i$$\n  Este é o modelo matemático que define uma Regressão Linear Simples, onde:\n  \n* $\\large y$ é o nosso vetor de observações da nossa variável resposta\n\n* $\\large \\beta_0$ é o **intercepto** (_intercept_) que representa o valor da função quando $X = 0$\n\n* $\\large \\beta_1$  é a **inclinação** (_slope_) que mede a mudança na variável $y$ para cada\nmudança de unidade da variável $X$\n\n* $\\large \\varepsilon_i$ é no nosso vetor de **erros aleatórios** ou **resíduos**, é toda variabilidade\nem $\\large y$ que não pode ser explicada por $X$\n\n## Regressão Linear Simples\n\nA regressão linear também possui premissas:\n\n\n1. As amostras devem ser independentes\n\n2. As unidades amostrais são selecionadas aleatoriamente\n\n3. Distribuição normal (gaussiana) **dos resíduos**\n\n4. Homogeneidade da variância **dos resíduos**\n\n\n## Regressão Linear Simples\n\n#### Exemplo\n\nAvaliaremos a relação entre o gradiente de temperatura média anual (°C) e o tamanho\nmédio do comprimento rostro-cloacal (CRC em mm) de populações de _Dendropsophus minutus_\n(Anura:Hylidae) amostradas em 109 localidades no Brasil.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nden_min <- ecodados::regressoes\n\nden_min |> glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 109\nColumns: 4\n$ Municipio    <chr> \"Acorizal\", \"Alpinopolis\", \"Alto_Paraiso\", \"Americana\", \"…\n$ CRC          <dbl> 22.98816, 22.91788, 21.97629, 23.32453, 22.83651, 20.8698…\n$ Temperatura  <dbl> 24.13000, 20.09417, 21.86167, 20.28333, 25.47333, 20.1216…\n$ Precipitacao <dbl> 1228.2, 1487.6, 1812.4, 1266.2, 2154.0, 1269.2, 1940.6, 1…\n```\n\n\n:::\n:::\n\n\n\n**Pergunta**: A temperatura afeta o tamanho do CRC de populações de _Dendropsophus minutus_?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_rls <- lm(CRC ~ Temperatura, data = den_min)\n```\n:::\n\n\nUtilizando a função `plot()` podemos fazer a inspeção visual dos resíduos e checar\na normalidade e a homogeneidade da variância.\n\n## Regressão Linear Simples\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2), oma = c(0, 0, 2, 0))\nplot(mod_rls)\n```\n\n::: {.cell-output-display}\n![](intro_tidy_slides_files/figure-revealjs/unnamed-chunk-67-1.png){width=960}\n:::\n:::\n\n\n\n\n## Regressão Linear Simples\n\nConfirmado que nossos dados atendem as premissas de normalidade e heterocedasticidade\ndos resíduos, podemos agora ver os resultados da nossa regressão usando as funções\n`anova()` e `summary()`. Falaremos de ANOVA (Análise de Variância) na próxima sessão,\nmas a função `anova()` quando fornecida um único modelo nos retorna a famosa Tabela\nda Anova, que nos mostra se os termos do nosso modelo foram significativos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mod_rls)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: CRC\n             Df  Sum Sq Mean Sq F value    Pr(>F)    \nTemperatura   1  80.931  80.931   38.92 9.011e-09 ***\nResiduals   107 222.500   2.079                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## Regressão Linear Simples\n\nA nossa velha amiga `summary()` nos fornece também a significância dos termos do\nmodelo, e ainda os valores dos coeficientes, e do coeficiente de determinação ($R^2$),\nque indica o quanto da variação em $y$ é explicada pela nossa variável $X$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod_rls)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = CRC ~ Temperatura, data = den_min)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.4535 -0.7784  0.0888  0.9168  3.1868 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 16.23467    0.91368  17.768  < 2e-16 ***\nTemperatura  0.26905    0.04313   6.239 9.01e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.442 on 107 degrees of freedom\nMultiple R-squared:  0.2667,\tAdjusted R-squared:  0.2599 \nF-statistic: 38.92 on 1 and 107 DF,  p-value: 9.011e-09\n```\n\n\n:::\n:::\n\n\n## Regressão Linear Simples\n\nPodemos apresentar nossos resultados por meio de um gráfico de dispersão como vimos\nanteriormente.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = den_min, aes(x = Temperatura, y = CRC)) +\nlabs(x = \"Temperatura média anual (°C)\",\ny = \"Comprimento rostro-cloacal (mm)\") +\ngeom_smooth(method = lm, se = FALSE,\n            color = \"#413c58\", alpha = 0.8) +\ngeom_point(size = 4, shape = 21,\n           fill = \"#988683\", color=\"#5c5c5e\", alpha = 0.8) +\ntheme_classic(base_size = 14, base_family = \"Ubuntu\") +\ntheme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](intro_tidy_slides_files/figure-revealjs/unnamed-chunk-71-1.png){width=960}\n:::\n:::\n\n\n## Regressão Linear Simples\n\n#### Interpretando os resultados\n\nAqui vale comentar sobre as diferentes hipóteses que são testadas em cada função.\n\nA função `summary()` realiza um teste $t$ para cada um dos betas do modelo, no\nnosso caso de uma regressão linear simples o intercepto e o slope. A hipótese nula\nneste caso é:\n\n$$H_0: \\beta_i = 0 \\quad versus \\quad H_a: \\beta_i \\neq 0$$\n\nOu seja, o teste avalia se a variável explicativa $X$ tem efeito significativo sobre \n$y$ controlando pelas outras variáveis do modelo.\n\n## Regressão Linear Simples\n\n#### Interpretando os resultados\n\nJá a função `anova()` está fazendo uma análise de variância (ANOVA) que testa a \nseguinte hipótese nula global de que todos os coeficientes, exceto o intercepto,\nsão iguais a zero:\n\n$$H_0: \\beta_1 = \\beta_2 = \\cdots \\beta_n =  0$$\n\nMas como falamos de uma regressão linear **simples**, testamos somente o nosso $\\beta_1$.\n\nOu seja, o teste $F$ da ANOVA **avalia se o modelo completo com as variáveis preditoras explica significativamente mais variância do que um modelo nulo** (só com o intercepto).\n\nSe o valor-p do teste $F$ for pequeno, rejeitamos $H_0$ e concluímos que **pelo menos \numa variável tem efeito significativo sobre a resposta**.\n\n## Análise de Variância (ANOVA)\n\nAnálise de variância com um fator é uma técnica de teste de hipótese usada para\ncomparar as médias de três ou mais populações. A análise de variância geralmente\né abreviada como ANOVA.\n\nComo mencionado anteriormente, a ANOVA é um teste de razão de variâncias. O que a\nestatistica do teste avalia de maneira resumida:\n\n$$Estatística \\ do \\ Teste = \\frac{Variância \\ dentro \\ dos \\ grupos}{Variância \\ entre \\ grupos}$$\n\nA **Estatística $F$** é o quociente destas duas variâncias, e nossa hipótese nula\nna ANOVA testa se a média dos grupos é igual:\n\n$$H_0: \\mu_1 = \\mu_2 = \\cdots \\mu_n$$\n\n**Premissas da ANOVA**:\n\n1. As amostras devem ser independentes\n2. As unidades amostrais são selecionadas aleatoriamente\n3. Distribuição normal (gaussiana) dos resíduos\n4. Homogeneidade da variância\n\n\n## Análise de Variância (ANOVA)\n\n#### Tabela da ANOVA\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qjexmnitzl\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qjexmnitzl table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qjexmnitzl thead, #qjexmnitzl tbody, #qjexmnitzl tfoot, #qjexmnitzl tr, #qjexmnitzl td, #qjexmnitzl th {\n  border-style: none;\n}\n\n#qjexmnitzl p {\n  margin: 0;\n  padding: 0;\n}\n\n#qjexmnitzl .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 90%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qjexmnitzl .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qjexmnitzl .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qjexmnitzl .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qjexmnitzl .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qjexmnitzl .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qjexmnitzl .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qjexmnitzl .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qjexmnitzl .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qjexmnitzl .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qjexmnitzl .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qjexmnitzl .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qjexmnitzl .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qjexmnitzl .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qjexmnitzl .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qjexmnitzl .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qjexmnitzl .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qjexmnitzl .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qjexmnitzl .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qjexmnitzl .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qjexmnitzl .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qjexmnitzl .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qjexmnitzl .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qjexmnitzl .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qjexmnitzl .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qjexmnitzl .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qjexmnitzl .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qjexmnitzl .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qjexmnitzl .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qjexmnitzl .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qjexmnitzl .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qjexmnitzl .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qjexmnitzl .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qjexmnitzl .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qjexmnitzl .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qjexmnitzl .gt_left {\n  text-align: left;\n}\n\n#qjexmnitzl .gt_center {\n  text-align: center;\n}\n\n#qjexmnitzl .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qjexmnitzl .gt_font_normal {\n  font-weight: normal;\n}\n\n#qjexmnitzl .gt_font_bold {\n  font-weight: bold;\n}\n\n#qjexmnitzl .gt_font_italic {\n  font-style: italic;\n}\n\n#qjexmnitzl .gt_super {\n  font-size: 65%;\n}\n\n#qjexmnitzl .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qjexmnitzl .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qjexmnitzl .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qjexmnitzl .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qjexmnitzl .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qjexmnitzl .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qjexmnitzl .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qjexmnitzl .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#qjexmnitzl div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black;\" scope=\"col\" id=\"fv\"><span data-qmd-base64=\"KipGb250ZXMgZGUgVmFyaWHDp8OjbyAoRlYpKio=\"><span class='gt_from_md'><strong>Fontes de Variação (FV)</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\" scope=\"col\" id=\"gl\"><span data-qmd-base64=\"KipHcmF1cyBkZSBMaWJlcmRhZGUgKEdMKSoq\"><span class='gt_from_md'><strong>Graus de Liberdade (GL)</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\" scope=\"col\" id=\"sq\"><span data-qmd-base64=\"KipTb21hIGRlIFF1YWRyYWRvcyAoU1EpKio=\"><span class='gt_from_md'><strong>Soma de Quadrados (SQ)</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\" scope=\"col\" id=\"qm\"><span data-qmd-base64=\"KipRdWFkcmFkbyBNw6lkaW8gKFFNKSoq\"><span class='gt_from_md'><strong>Quadrado Médio (QM)</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\" scope=\"col\" id=\"stat\"><span data-qmd-base64=\"KioqRioqKg==\"><span class='gt_from_md'><em><strong>F</strong></em></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"fv\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black;\"><span data-qmd-base64=\"VHJhdGFtZW50bzxicj4oZW50cmUp\"><span class='gt_from_md'>Tratamento<br>(entre)</span></span></td>\n<td headers=\"gl\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\"><span data-qmd-base64=\"JHAtMSQ=\"><span class='gt_from_md'>\\(p-1\\)</span></span></td>\n<td headers=\"sq\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\"><span data-qmd-base64=\"JFNRX3tUcmF0fSQ=\"><span class='gt_from_md'>\\(SQ_{Trat}\\)</span></span></td>\n<td headers=\"qm\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\"><span data-qmd-base64=\"JFxmcmFje1NRX3tUcmF0fX17cC0xfSQ=\"><span class='gt_from_md'>\\(\\frac{SQ_{Trat}}{p-1}\\)</span></span></td>\n<td headers=\"stat\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\"><span data-qmd-base64=\"JFxmcmFje1FNX3tUcmF0fX17UU1fe1Jlc319JA==\"><span class='gt_from_md'>\\(\\frac{QM_{Trat}}{QM_{Res}}\\)</span></span></td></tr>\n    <tr><td headers=\"fv\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black;\"><span data-qmd-base64=\"RXJybyBFeHBlcmltZW50YWw8YnI+KGRlbnRybyk=\"><span class='gt_from_md'>Erro Experimental<br>(dentro)</span></span></td>\n<td headers=\"gl\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\"><span data-qmd-base64=\"JG4tcCQ=\"><span class='gt_from_md'>\\(n-p\\)</span></span></td>\n<td headers=\"sq\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\"><span data-qmd-base64=\"JFNRX3tSZXN9JA==\"><span class='gt_from_md'>\\(SQ_{Res}\\)</span></span></td>\n<td headers=\"qm\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\"><span data-qmd-base64=\"JFxmcmFje1NRX3tSZXN9fXtuLXB9JA==\"><span class='gt_from_md'>\\(\\frac{SQ_{Res}}{n-p}\\)</span></span></td>\n<td headers=\"stat\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\"><br /></td></tr>\n    <tr><td headers=\"fv\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black;\"><span data-qmd-base64=\"KipUb3RhbCoq\"><span class='gt_from_md'><strong>Total</strong></span></span></td>\n<td headers=\"gl\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\"><span data-qmd-base64=\"JG4tMSQ=\"><span class='gt_from_md'>\\(n-1\\)</span></span></td>\n<td headers=\"sq\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\"><span data-qmd-base64=\"JFNRX3tUb3RhbH0k\"><span class='gt_from_md'>\\(SQ_{Total}\\)</span></span></td>\n<td headers=\"qm\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\"><br /></td>\n<td headers=\"stat\" class=\"gt_row gt_center\" style=\"border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; text-align: center;\"><br /></td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nEsta é a famosa tabela da ANOVA, a mesma tabela que é retornada pelas funções\nque utilizaremos aqui no R. As somas de quadrado podem ser obtidas como:\n\n:::{.columns}\n:::{.column  width=\"\"}\n$\\small \\displaystyle SQ_{Total} = \\sum_{i=1,j=1}^{I,J}Y_{ij}^2 - \\frac{\\displaystyle \\left( \\sum_{i=1,j=1}^{I,J}Y_{ij}\\right)^2}{IJ}$\n:::\n:::{.column  width=\"\"}\n$\\small \\displaystyle SQ_{Trat} = \\sum_{i=1}^{I}\\frac{T_{i}^2}{J} - \\frac{\\displaystyle \\left( \\sum_{i=1,j=1}^{I,J}Y_{ij}\\right)^2}{IJ}$\n:::\n:::\n\n$\\small SQ_{Total} \\ = \\ SQ_{Trat} + SQ_{Res}$\n\n## Anova de um Fator\n\nNa ANOVA de um fator testamos o efeito de uma única variável categórica (Tratamento)\nsobre nossa variável dependente ($y$).\n\n**Pergunta**: Existe diferença no tamanho do bico (`bill_length_mm`) entre as diferentes\nespécies de pinguim?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npinguins <- palmerpenguins::penguins\n\npinguins |>\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n  <fct>   <fct>              <dbl>         <dbl>             <int>       <int>\n1 Adelie  Torgersen           39.1          18.7               181        3750\n2 Adelie  Torgersen           39.5          17.4               186        3800\n3 Adelie  Torgersen           40.3          18                 195        3250\n4 Adelie  Torgersen           NA            NA                  NA          NA\n5 Adelie  Torgersen           36.7          19.3               193        3450\n6 Adelie  Torgersen           39.3          20.6               190        3650\n# ℹ 2 more variables: sex <fct>, year <int>\n```\n\n\n:::\n:::\n\n\n## Anova de um Fator\n\nDiferente da última sessão, utilizaremos a função `aov()` para realizarmos a ANOVA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_bico <- aov(bill_length_mm ~ species, data = pinguins)\n```\n:::\n\n\n#### Testando Premissas\n\nAssim como fizemos com nosso modelo de regressão linear podemos avaliar nossos\nresíduos visualmente.\n\n\n::: {.cell layout-align=\"center\" lightbox='{\"group\":\"r-graph\"}'}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2), oma = c(0, 0, 2, 0))\nplot(anova_bico)\n```\n\n::: {.cell-output-display}\n![](intro_tidy_slides_files/figure-revealjs/unnamed-chunk-75-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n\n## Anova de um Fator\n\nNossos resíduos parecem seguir normalidade e homocedasticidade. Mas podemos confirmar\nrealizando os testes de Shapiro-Wilk (normalidade) e Bartlett (homocedasticidade).\n\n[{{< fa circle-exclamation >}} **Lembre-se que sempre testamos os resíduos!**]{.content-visible when-format=\"html\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(residuals(anova_bico))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(anova_bico)\nW = 0.98903, p-value = 0.01131\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbartlett.test(bill_length_mm ~ species, data = pinguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  bill_length_mm by species\nBartlett's K-squared = 5.6179, df = 2, p-value = 0.06027\n```\n\n\n:::\n:::\n\n\nLembrando que a hipótese nula em ambos os testes é de que os dados seguem \nnormalidade/homocedasticidade. Confirmamos assim o nosso diagnístico visual.\n\n## Anova de um Fator\n\n### Tabela Anova\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(anova_bico)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \nspecies       2   7194    3597   410.6 <2e-16 ***\nResiduals   339   2970       9                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n2 observations deleted due to missingness\n```\n\n\n:::\n:::\n\n\nE aqui obtemos a nossa tabela da ANOVA. E com base no p-valor obtido podemos confirmar\nque existe efeito de Espécie sobre o Tamanho do Bico dos Pinguins. Em relação a nossa\nhipótese nula, isso significa dizer que **pelo menos um dos grupos avaliados possui\nmédia diferente dos demais**.\n\n\n## Anova de um Fator - Comparação de Médias\n\nUma vez sabendo que existe diferença significativa, agora precisamos realizar um\npós-teste de comparação de médias entre os grupos. Para isso vamos utilizar o\npacote `agricolae`. Este pacote é excelente por possuir diversos pos-testes para\nanova, entre eles Tukey, SNK, e Duncan. \n\n**Tukey HSD **\n\nO Teste **Tukey HSD (_honestly significant difference_)** é amplamente reconhecido por controlar de forma rigorosa a taxa de erro familiar, permitindo comparações par a par entre todas as médias com um critério bastante robusto.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagricolae::HSD.test(anova_bico,\"species\", group=TRUE, console=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nStudy: anova_bico ~ \"species\"\n\nHSD Test for bill_length_mm \n\nMean Square Error:  8.760732 \n\nspecies,  means\n\n          bill_length_mm      std   r        se  Min  Max   Q25   Q50    Q75\nAdelie          38.79139 2.663405 151 0.2408694 32.1 46.0 36.75 38.80 40.750\nChinstrap       48.83382 3.339256  68 0.3589349 40.9 58.0 46.35 49.55 51.075\nGentoo          47.50488 3.081857 123 0.2668810 40.9 59.6 45.30 47.30 49.550\n\nAlpha: 0.05 ; DF Error: 339 \nCritical Value of Studentized Range: 3.329136 \n\nGroups according to probability of means differences and alpha level( 0.05 )\n\nTreatments with the same letter are not significantly different.\n\n          bill_length_mm groups\nChinstrap       48.83382      a\nGentoo          47.50488      b\nAdelie          38.79139      c\n```\n\n\n:::\n:::\n\n\n## Anova de um Fator - Comparação de Médias\n\n**SNK**\n\nO Teste **Student-Newman-Keuls (SNK)** realiza comparações par a par de maneira sequencial,\nequilibrando a sensibilidade para detectar diferenças com um critério menos conservador\nque o Tukey HSD, mas mais rigoroso que o teste de Duncan.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagricolae::SNK.test(anova_bico, \"species\", group = TRUE, console = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nStudy: anova_bico ~ \"species\"\n\nStudent Newman Keuls Test\nfor bill_length_mm \n\nMean Square Error:  8.760732 \n\nspecies,  means\n\n          bill_length_mm      std   r        se  Min  Max   Q25   Q50    Q75\nAdelie          38.79139 2.663405 151 0.2408694 32.1 46.0 36.75 38.80 40.750\nChinstrap       48.83382 3.339256  68 0.3589349 40.9 58.0 46.35 49.55 51.075\nGentoo          47.50488 3.081857 123 0.2668810 40.9 59.6 45.30 47.30 49.550\n\nGroups according to probability of means differences and alpha level( 0.05 )\n\nMeans with the same letter are not significantly different.\n\n          bill_length_mm groups\nChinstrap       48.83382      a\nGentoo          47.50488      b\nAdelie          38.79139      c\n```\n\n\n:::\n:::\n\n\n## Anova de um Fator - Comparação de Médias\n\n**Duncan**\n\nO Teste de **Duncan** adota uma abordagem mais liberal, facilitando a identificação\nde intervalos de similaridade entre as médias, mas com uma margem maior de\nrisco de erro do Tipo I.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagricolae::duncan.test(anova_bico, \"species\", group = TRUE, console = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nStudy: anova_bico ~ \"species\"\n\nDuncan's new multiple range test\nfor bill_length_mm \n\nMean Square Error:  8.760732 \n\nspecies,  means\n\n          bill_length_mm      std   r        se  Min  Max   Q25   Q50    Q75\nAdelie          38.79139 2.663405 151 0.2408694 32.1 46.0 36.75 38.80 40.750\nChinstrap       48.83382 3.339256  68 0.3589349 40.9 58.0 46.35 49.55 51.075\nGentoo          47.50488 3.081857 123 0.2668810 40.9 59.6 45.30 47.30 49.550\n\nGroups according to probability of means differences and alpha level( 0.05 )\n\nMeans with the same letter are not significantly different.\n\n          bill_length_mm groups\nChinstrap       48.83382      a\nGentoo          47.50488      b\nAdelie          38.79139      c\n```\n\n\n:::\n:::\n\n\n## Anova de um Fator - Comparação de Médias\n\n**Dunnet**\n\nO Teste **Dunnett** é particularmente útil quando o objetivo principal é comparar\ncada tratamento com um grupo de controle, focando essa análise e ajustando\nas comparações para esse propósito.\n\nPara realizar esse teste usaremos o pacote `multcomp`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmultcomp::glht(anova_bico, linfct = multcomp::mcp(species= \"Dunnett\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t General Linear Hypotheses\n\nMultiple Comparisons of Means: Dunnett Contrasts\n\n\nLinear Hypotheses:\n                        Estimate\nChinstrap - Adelie == 0   10.042\nGentoo - Adelie == 0       8.713\n```\n\n\n:::\n:::\n\n\n## Anova de um Fator\n\n**Apresentando os resultados**\n\nAlém da apresentação da tabela podemos reportar nossos resultados graficamente\ncom boxplots e adicionar os grupos do teste de Tukey.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(ggtext)\n\ngrupos <- tibble(species = factor(c(\"Adelie\", \"Chinstrap\", \"Gentoo\")),\n                 grupos = c(\"C\",\"A\",\"B\"),\n                 ymax = c(48,59,58))\n\ntukey <- tibble(species = \"Adelie\",\n                label = \"<b>TukeyHSD</b><br>MSE: 8.76<br>p < 0.05<br>q<sub>a</sub>: 3.329\",\n                y = 55)\n\npinguins |>\n  ggplot(aes(x=species, y=bill_length_mm, fill = species)) +\n  geom_boxplot(outliers = FALSE)+\n  annotate(\"text\", x=grupos$species,\n           y = grupos$ymax, \n           label = grupos$grupos,\n           family = \"Ubuntu\",\n            size = 5) +\n  geom_richtext(data = tukey, aes(x = species, y = 55, label = label),\n                fill = NA) +\n  theme_classic(base_size = 14, base_family = \"Ubuntu\") +\n  theme(legend.position = \"none\") +\n  labs(title = \"Variação do Comprimento de Bico em Pinguins\",\n       x = \"Espécies\",\n       y = \"Comprimento do Bico (mm)\")\n```\n\n::: {.cell-output-display}\n![](intro_tidy_slides_files/figure-revealjs/unnamed-chunk-84-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## Bonus > Anova vs Teste T\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(CRC ~ Estacao,\n                  data = crc_phy_nat,\n                  var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  CRC by Estacao\nt = 4.1524, df = 49, p-value = 0.000131\nalternative hypothesis: true difference in means between group Chuvosa and group Seca is not equal to 0\n95 percent confidence interval:\n 0.2242132 0.6447619\nsample estimates:\nmean in group Chuvosa    mean in group Seca \n             3.695357              3.260870 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov(CRC ~ Estacao, data = crc_phy_nat) |>\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nEstacao      1  2.384  2.3838   17.24 0.000131 ***\nResiduals   49  6.774  0.1383                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## That's all folks!\n\n\n\n:::{.center-col}\n\n![](images/the-office-michael.gif){width=\"600\"}\n<br>\n\n{{< fa envelope >}} pbarrosbio@gmail.com\n\n{{< fa link >}} https://paulobarros.com.br\n\n<br>\n\n#### Obrigado pela paciência! \n\n:::\n\n## Referências\n",
    "supporting": [
      "intro_tidy_slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}